### ISSUE TITLE
Sort data by date[time] field in a descending order 

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#23]
By default, data should be sorted by date[time] field in a descending order so that latest data is visible in the preview.

## Tasks

* [x] Change default query so it fetches data sorted by date[time] (UTC) field in a descending order

**Comment by steveoni** [comment]
@anuveyatsu should this be available only when users filter or it should also be included in the default loading of data also?

**Comment by anuveyatsu** [comment]
@steveoni it should be loaded by default, eg, see the current state - https://www.energidataservice.dk/tso-electricity/electricitysupplierspergridarea

**Comment by anuveyatsu** [comment]
FIXED in #26
