### ISSUE TITLE
Filter bugs

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer-graphql#34]
Below is the screen recording to demo number of bugs I've identified:

* Datepicker element is empty after submitting the filter with start date: https://www.awesomescreenshot.com/video/3187265?key=e54655670031e1c17ee760c7188f8c0f. I'd expect it to have the value that is used to filter (date = 2021-03-01 ...)
* App crashes when I try to filter by a field: https://www.awesomescreenshot.com/video/3187282?key=7c8f7493a839f09df4179894605545b3

## Tasks

* [ ] Create tests to cover each bug cases
* [ ] Implement fixes

**Comment by anuveyatsu** [comment]
Any updates here @cotts @steveoni ?

**Comment by steveoni** [comment]
we've fixed the second bug , but @cotts is fixing the first and wrapping all up.

I discover another bug, I will create and issue for that and start working on it this evening

**Comment by cotts** [comment]
@anuveyatsu , sorry about the delay.. I sent the PR about the first issue

**Comment by anuveyatsu** [comment]
@cotts I've left comments in the PR #37 so I think it is also relevant to @steveoni
